version: '3.9'

services:
  activemq:
    container_name: activemq-test
    hostname: localhost
    image: apache/activemq-classic:5.17.6
    ports:
      - 61616:61616
      - 8161:8161
      - 5672:5672
      - 5671:5671
    volumes:
      - ./activemq/data:/data/activemq
      - ./activemq/log:/var/log/activemq
    restart: on-failure
