version: '3.9'

services:
  activemq:
    container_name: activemq-test
    hostname: localhost
    build: 
      context: .
      dockerfile: activemq.Dockerfile
    ports:
      - 61616:61616
      - 8161:8161
      - 5672:5672
      - 5671:5671
    volumes:
      - ./activemq/data:/data/activemq
      - ./activemq/log:/var/log/activemq
    restart: on-failure
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
